int _putchar(char c);
void *malloc_checked(unsigned int b);
char *string_nconcat(char *s1, char *s2, unsigned int n);
void *_calloc(unsigned int nmemb, unsigned int size);
int *array_range(int min, int max);
void mul(char *num1, char *num2);
int str_isdigit(char *str);
int _strlen(char *s);
void print_result(int len1, int len2, int *result);
void calculate_product(char *num1, char *num2, int len1, int len2, int *result);
